-- Bistooltip_Whitemane_Frostmourne/main.lua
-- Server diff for Whitemane: Frostmourne. Generated 2026-09-08 from:
--   * EmblemData.lua custom currencies (Emblem of Ascension / Ascension II /
--     Echo of the Titans) — moved OUT of core per spec W6 (core = clean WotLK)
--   * docs/superpowers/data/whitemane-custom-extract-2026-09-08.lua:
--     27 rank-1 legendary overrides (128858/130023/130031/131004/150005),
--     expressed as DB-independent SetBiSSlotRank ("rank 1 = legendary"),
--     so they survive ranking updates and database switches
--   * typo fix (owner Q2): EmblemData [15000] emitted as 150005
-- Vendor location labels: pending owner scans (D6) — VENDOR lines carry
-- currency costs only, no location needed.
-- Pure Lua 5.1; loads after Bistooltip (hard ## Dependencies).

local P = "Bistooltip_Whitemane_Frostmourne"
BisTooltip:SetBiSSlotRank("Druid", "Balance", "T7", "Weapon", 1, 130023, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Druid", "Balance", "T8", "Weapon", 1, 130023, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Druid", "Feral dps", "T8", "Weapon", 1, 128858, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Hunter", "Beast mastery", "T7", "Ranged", 1, 150005, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Hunter", "Marksmanship", "T7", "Ranged", 1, 150005, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Hunter", "Survival", "T7", "Ranged", 1, 150005, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Mage", "Arcane", "T7", "Weapon", 1, 130023, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Mage", "Arcane", "T8", "Weapon", 1, 130023, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Mage", "Fire", "T7", "Weapon", 1, 130023, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Mage", "Fire", "T8", "Weapon", 1, 130023, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Mage", "Fire FFB", "T7", "Weapon", 1, 130023, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Mage", "Fire FFB", "T8", "Weapon", 1, 130023, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Mage", "Frost", "T7", "Weapon", 1, 130023, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Mage", "Frost", "T8", "Weapon", 1, 130023, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Paladin", "Retribution", "T7", "Weapon", 1, 130031, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Paladin", "Retribution", "T8", "Weapon", 1, 130031, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Paladin", "Retribution", "T9", "Weapon", 1, 130031, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Priest", "Shadow", "T7", "Weapon", 1, 130023, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Priest", "Shadow", "T8", "Weapon", 1, 130023, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Shaman", "Enhancement", "T8", "Weapon", 1, 131004, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Shaman", "Enhancement", "T9", "Weapon", 1, 131004, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Warrior", "Arms", "T7", "Weapon", 1, 130031, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Warrior", "Arms", "T8", "Weapon", 1, 130031, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Warrior", "Arms", "T9", "Weapon", 1, 130031, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Warrior", "Fury", "T7", "Weapon", 1, 130031, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Warrior", "Fury", "T8", "Weapon", 1, 130031, P) -- legendary rank-1
BisTooltip:SetBiSSlotRank("Warrior", "Fury", "T9", "Weapon", 1, 130031, P) -- legendary rank-1

-- Custom-currency vendor costs (from EmblemData, W6 cutover)
BisTooltip:AddAcquisition(39701, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(39702, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(39703, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(39704, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(39706, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(39717, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(39718, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(39719, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(39720, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(39721, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(39722, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(39723, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(39724, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(39725, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(39726, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(39727, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(39728, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 12 } } }, P)
BisTooltip:AddAcquisition(39729, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(39731, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(39732, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(39733, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(39734, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(39735, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(39756, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(39757, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 12 } } }, P)
BisTooltip:AddAcquisition(39759, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(39760, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(39761, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(39762, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(39764, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(39765, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(39767, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(39768, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40061, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40062, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40063, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40064, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40065, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40069, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40071, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40074, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40075, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40080, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40107, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40108, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40184, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40185, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40186, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40187, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40188, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40191, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 12 } } }, P)
BisTooltip:AddAcquisition(40193, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40194, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40196, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40197, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40198, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40200, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40201, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40203, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40204, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40205, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40206, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40207, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 12 } } }, P)
BisTooltip:AddAcquisition(40209, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40210, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40234, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40235, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40236, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40237, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40238, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40239, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 12 } } }, P)
BisTooltip:AddAcquisition(40240, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40241, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40242, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40243, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40244, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40246, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40247, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40249, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40250, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40251, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40252, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40253, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40254, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40255, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40256, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40257, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40258, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40259, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40260, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40261, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40262, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40263, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40267, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 12 } } }, P)
BisTooltip:AddAcquisition(40268, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 12 } } }, P)
BisTooltip:AddAcquisition(40269, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40270, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40271, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40272, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40274, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40275, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40277, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40278, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40279, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40282, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40283, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40286, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40287, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40288, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40289, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40294, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40296, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40297, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40298, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40299, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40301, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40302, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40303, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40304, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40305, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40306, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40315, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40316, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40317, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40318, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40319, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40320, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40321, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 12 } } }, P)
BisTooltip:AddAcquisition(40322, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 12 } } }, P)
BisTooltip:AddAcquisition(40323, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40324, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40325, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40326, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40327, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40329, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40330, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40332, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40334, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40344, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40347, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40349, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40351, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40352, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40362, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40363, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40365, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40366, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40367, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40369, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40370, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40371, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40372, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40373, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40374, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40375, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40376, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40377, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40378, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40379, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40380, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40381, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40382, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40383, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40384, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40385, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40386, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40387, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40388, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40395, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40396, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40398, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40399, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40400, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40401, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40402, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40403, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40405, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40431, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40432, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40433, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 15 } } }, P)
BisTooltip:AddAcquisition(40437, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40438, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40439, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40446, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40451, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40453, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40531, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40532, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40539, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40541, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40543, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40549, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40555, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40558, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40560, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40561, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40562, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40564, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40566, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40588, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40589, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40590, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40591, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40592, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40594, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40602, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40626, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40629, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(40632, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(40635, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 25 } } }, P)
BisTooltip:AddAcquisition(40638, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(44003, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(44004, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 19 } } }, P)
BisTooltip:AddAcquisition(44005, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(44006, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(44007, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(44008, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(44011, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 38 } } }, P)
BisTooltip:AddAcquisition(45111, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45112, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45132, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 44 } } }, P)
BisTooltip:AddAcquisition(45133, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45134, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45135, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45136, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45137, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45139, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45148, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45158, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45228, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45241, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45242, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45243, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45244, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45245, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45247, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45250, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45251, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45262, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45271, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45286, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45293, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45294, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45295, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45296, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45297, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45300, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45308, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45319, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45326, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45334, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45442, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 44 } } }, P)
BisTooltip:AddAcquisition(45443, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45444, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45445, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45446, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45447, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45448, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45449, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45451, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45456, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45457, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 52 } } }, P)
BisTooltip:AddAcquisition(45459, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45460, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45461, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45462, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45466, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45469, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45470, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45471, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45472, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45473, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45474, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45481, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45484, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 44 } } }, P)
BisTooltip:AddAcquisition(45485, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45486, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45487, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45488, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45490, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45494, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45495, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45496, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45497, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45502, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45516, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 52 } } }, P)
BisTooltip:AddAcquisition(45517, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45518, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 44 } } }, P)
BisTooltip:AddAcquisition(45519, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45520, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45533, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 52 } } }, P)
BisTooltip:AddAcquisition(45534, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45535, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 44 } } }, P)
BisTooltip:AddAcquisition(45536, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45537, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45540, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45542, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45570, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 52 } } }, P)
BisTooltip:AddAcquisition(45587, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45594, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45599, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45609, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 44 } } }, P)
BisTooltip:AddAcquisition(45610, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45611, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45612, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 44 } } }, P)
BisTooltip:AddAcquisition(45613, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 52 } } }, P)
BisTooltip:AddAcquisition(45615, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45616, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45617, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45619, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45620, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 44 } } }, P)
BisTooltip:AddAcquisition(45633, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45639, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45642, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 19 } } }, P)
BisTooltip:AddAcquisition(45654, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 25 } } }, P)
BisTooltip:AddAcquisition(45657, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 19 } } }, P)
BisTooltip:AddAcquisition(45663, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45665, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 32 } } }, P)
BisTooltip:AddAcquisition(45703, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45867, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45868, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45869, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45870, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45871, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45876, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45877, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45886, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45887, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45888, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45928, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45929, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45930, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45931, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45933, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45943, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45945, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45946, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45947, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45982, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45988, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45989, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45990, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(45993, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46017, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 150 } } }, P)
BisTooltip:AddAcquisition(46021, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46032, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46033, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46034, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46035, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46036, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46037, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46038, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46039, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46040, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46041, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46042, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46043, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46044, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46045, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46046, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46047, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46048, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46049, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46050, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46051, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46067, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46068, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46095, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46096, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(46097, { kind = "VENDOR", cost = { { currency = "Echo of the Titans", amount = 12 } } }, P)
BisTooltip:AddAcquisition(128858, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 150 } } }, P)
BisTooltip:AddAcquisition(130023, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 80 } } }, P)
BisTooltip:AddAcquisition(130031, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 80 } } }, P)
BisTooltip:AddAcquisition(131004, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 150 } } }, P)
BisTooltip:AddAcquisition(131008, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 1 } } }, P)
BisTooltip:AddAcquisition(131010, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension II", amount = 2 } } }, P)
BisTooltip:AddAcquisition(150005, { kind = "VENDOR", cost = { { currency = "Emblem of Ascension", amount = 80 } } }, P)
