-- tools/migrate_sources.lua
-- usage: lua5.1 tools/migrate_sources.lua
-- Offline migrator: lootTable + Bistooltip_emblem_items -> new source model.
-- Generates Bistooltip/SourceRegistry.lua + Bistooltip/ItemAcquisition.lua.
-- Canonical alias/difficulty cleanup happens in Task 3; difficulty stays "" here.
_G.FACTION_ALLIANCE = "Alliance"
_G.FACTION_HORDE = "Horde"
_G.SlashCmdList = {}
dofile("Bistooltip/Loot_Sources.lua") -- provides lootTable
dofile("Bistooltip/EmblemData.lua") -- provides Bistooltip_emblem_items
assert(type(lootTable) == "table", "lootTable missing after Loot_Sources.lua")
assert(type(Bistooltip_emblem_items) == "table", "Bistooltip_emblem_items missing after EmblemData.lua")

local registry, acquisition = {}, {}
local function sourceID(inst, diff, boss)
  return ((inst .. "_" .. (diff or "") .. "_" .. boss):gsub("[^%w]+", "_"):gsub("_+", "_"):upper())
end
for zone, bosses in pairs(lootTable) do
  for boss, items in pairs(bosses) do
    local id = sourceID(zone, "", boss) -- difficulty filled during canonical pass (Task 3)
    registry[id] = registry[id] or { instance = zone, boss = boss, difficulty = "" }
    for _, itemID in pairs(items) do
      if type(itemID) == "number" and itemID > 0 then
        acquisition[itemID] = acquisition[itemID] or {}
        table.insert(acquisition[itemID], { kind = "DROP", source = id })
      end
    end
  end
end
-- emblem items -> VENDOR entries (T9-245 trophy variant flagged in Task 3)
for itemID, e in pairs(Bistooltip_emblem_items or {}) do
  acquisition[itemID] = acquisition[itemID] or {}
  table.insert(acquisition[itemID], { kind = "VENDOR", cost = { { currency = e.currency, amount = e.cost } } })
end

-- serializer: sorted keys, %q strings, numbers only, no external deps
local function sortedKeys(t)
  local ks = {}
  for k in pairs(t) do ks[#ks + 1] = k end
  table.sort(ks)
  return ks
end

local HEADER = "-- Generated by tools/migrate_sources.lua - do not edit by hand.\n"

local function writeRegistry(path)
  local f = assert(io.open(path, "w"))
  f:write(HEADER)
  f:write("BisTooltip_SourceRegistry = {\n")
  for _, id in ipairs(sortedKeys(registry)) do
    local r = registry[id]
    f:write(string.format("  [%q] = { instance = %q, boss = %q, difficulty = %q },\n",
      id, r.instance, r.boss, r.difficulty))
  end
  f:write("}\nreturn BisTooltip_SourceRegistry\n")
  f:close()
end

local function writeAcquisition(path)
  local f = assert(io.open(path, "w"))
  f:write(HEADER)
  f:write("BisTooltip_ItemAcquisition = {\n")
  for _, itemID in ipairs(sortedKeys(acquisition)) do
    f:write(string.format("  [%d] = {\n", itemID))
    for _, e in ipairs(acquisition[itemID]) do
      if e.kind == "DROP" then
        f:write(string.format("    { kind = %q, source = %q },\n", e.kind, e.source))
      else -- VENDOR
        local c = e.cost[1]
        f:write(string.format("    { kind = %q, cost = { { currency = %q, amount = %d } } },\n",
          e.kind, c.currency, c.amount))
      end
    end
    f:write("  },\n")
  end
  f:write("}\nreturn BisTooltip_ItemAcquisition\n")
  f:close()
end

writeRegistry("Bistooltip/SourceRegistry.lua")
writeAcquisition("Bistooltip/ItemAcquisition.lua")

local nreg, nacq = 0, 0
for _ in pairs(registry) do nreg = nreg + 1 end
for _ in pairs(acquisition) do nacq = nacq + 1 end
print(string.format("migrated: %d sources, %d items", nreg, nacq))
