-- tools/tier_matrix.lua — committed tier facts for the migrator post-pass.
-- Provenance: Pazzions AtlasLoot oracle v5.11.04 (wrathofthelichking.lua),
-- downloaded transiently on 2026-09-08 (GPLv2, never committed; spec S4-2).
-- Relations cross-checked against WotLK lockout rules where possible.
--
-- Oracle anomalies (deliberate handling):
--  * ICC 10HC pages list normal marks — EXCLUDED here: single witness,
--    contradicts 10/25 mark lockouts (10-man ICC drops no marks).
--  * ICC 25HC pages list BOTH normal and heroic marks — INCLUDED as-is
--    (matches common private-server behaviour; owner plays private servers).
--
-- Class groups are the standard T7-T10 token families (verify in-game once;
-- the turn-in vendor groups classes identically across tiers).

local M = {}

-- class (as spelled in "Tier 10N <Class> ..." input zones) -> token family
M.CLASS_FAMILY = {
  Warrior = "Protector", Hunter = "Protector", Shaman = "Protector",
  Paladin = "Conqueror", Priest = "Conqueror", Warlock = "Conqueror",
  Rogue = "Vanquisher", DK = "Vanquisher", Mage = "Vanquisher", Druid = "Vanquisher",
}

-- T10 mark-dropping bosses (oracle: Saurfang/Putricide/Lanathel/
-- Sindragosa/LichKing 25Man + 25ManHEROIC pages; no other ICC boss
-- carries Mark of Sanctification rows)
M.ICC_MARK_BOSSES = {
  "Saurfang",
  "Putricide",
  "BQ Lana'thel",
  "Sindragosa",
  "Lich King",
}

-- Mark of Sanctification items: id -> {family, heroic}
M.MARKS = {
  [52025] = { family = "Vanquisher", heroic = false },
  [52026] = { family = "Protector",  heroic = false },
  [52027] = { family = "Conqueror",  heroic = false },
  [52028] = { family = "Vanquisher", heroic = true },
  [52029] = { family = "Protector",  heroic = true },
  [52030] = { family = "Conqueror",  heroic = true },
}

-- Boss-tied quest rewards (owner rule 2026-09-08): render "<Boss> [Quest]"
-- as a DROP from a dedicated source, difficulty per the quest's lockout.
-- 45614 Starshine Circle: oracle page UlduarAlgalon25Man (finger, 25-man).
M.QUEST_DROPS = {
  [45614] = { instance = "Ulduar", boss = "Algalon [Quest]", difficulty = "25N" },
}

-- Owner short-form boss names (2026-09-15 cosmetics pass). Applied by the
-- migrator at registry-build time so every source line uses them.
M.BOSS_SHORT = {
  -- Naxxramas
  ["Grand Widow Faerlina"] = "Faerlina",
  ["Instructor Razuvious"] = "Razuvious",
  ["Gothik the Harvester"] = "Gothik",
  ["The Four Horsemen"] = "4Horsemen",
  ["Noth the Plaguebringer"] = "Noth",
  ["Heigan the Unclean"] = "Heigan",
  -- VoA
  ["Archavon the Stone Watcher"] = "Archavon",
  ["Emalon the Storm Watcher"] = "Emalon",
  ["Koralon the Flame Watcher"] = "Koralon",
  ["Toravon the Ice Watcher"] = "Toravon",
  -- Ulduar
  ["Flame Leviathan"] = "Leviathan",
  ["Ignis the Furnace Master"] = "Ignis",
  ["Lord Marrowgar"] = "Marrowgar",
  ["Lady Deathwhisper"] = "Lady",
  ["XT-002 Deconstructor"] = "XT",
  ["Assembly of Iron"] = "Assembly",
  ["General Vezax"] = "Vezax",
  ["Yogg-Saron"] = "Yogg",
  ["Algalon the Observer"] = "Algalon",
  -- TOC / TOGC
  ["Beasts of Northrend"] = "Beasts",
  ["Lord Jaraxxus"] = "Jaraxxus",
  ["Faction Champions"] = "Champions",
  ["Twin Val'kyr"] = "Twins",
  -- ICC
  ["Gunship Battle"] = "Gunship",
  ["Deathbringer Saurfang"] = "Saurfang",
  ["Professor Putricide"] = "Putricide",
  ["Blood Prince Council"] = "BP Council",
  ["Blood-Queen Lana'thel"] = "BQ Lana'thel",
  ["Valithria Dreamwalker"] = "Valithria",
  ["The Lich King"] = "Lich King",
}

-- T7 "Lost" set: which bosses drop which token slot (oracle: Naxx80 pages +
-- Sartharion; hands from Sartharion, legs chest Gluth/Noth/Heigan/Thaddius/
-- 4Horsemen, shoulders Loatheb, heads Kel'Thuzad).
-- T8 "Wayward" set: Ulduar bosses (oracle: Freya/Hodir/Mimiron/Thorim/Yogg
-- pages — chest Yogg+Hodir? per oracle rows below in TOKEN_DROPS).
-- Shape: [itemID] = { tier, family, slot, sources = { {instance, bossPage, diff}, ... } }
-- slot derived from the token name prefix at build time; we list pages only.
M.TOKEN_PAGES = {
  -- T7 hands (10: 40613-15 @ Sartharion10; 25: 40628-30 @ Sartharion25)
  [40613] = { slot = "Hands", tier = "T7", family = "Lost Conqueror",  pages = { { "Obsidian Sanctum", "Sartharion", "10N" } } },
  [40614] = { slot = "Hands", tier = "T7", family = "Lost Protector",  pages = { { "Obsidian Sanctum", "Sartharion", "10N" } } },
  [40615] = { slot = "Hands", tier = "T7", family = "Lost Vanquisher", pages = { { "Obsidian Sanctum", "Sartharion", "10N" } } },
  [40628] = { slot = "Hands", tier = "T7", family = "Lost Conqueror",  pages = { { "Obsidian Sanctum", "Sartharion", "25N" } } },
  [40629] = { slot = "Hands", tier = "T7", family = "Lost Protector",  pages = { { "Obsidian Sanctum", "Sartharion", "25N" } } },
  [40630] = { slot = "Hands", tier = "T7", family = "Lost Vanquisher", pages = { { "Obsidian Sanctum", "Sartharion", "25N" } } },
  -- T7 legs (10: Gluth/Noth/Heigan 40619-21; 25: Gluth/Thaddius/4H 40634-36)
  [40619] = { slot = "Legs", tier = "T7", family = "Lost Conqueror",  pages = { { "Naxxramas", "Gluth", "10N" }, { "Naxxramas", "Noth", "10N" }, { "Naxxramas", "Heigan", "10N" } } },
  [40620] = { slot = "Legs", tier = "T7", family = "Lost Protector",  pages = { { "Naxxramas", "Gluth", "10N" }, { "Naxxramas", "Noth", "10N" }, { "Naxxramas", "Heigan", "10N" } } },
  [40621] = { slot = "Legs", tier = "T7", family = "Lost Vanquisher", pages = { { "Naxxramas", "Gluth", "10N" }, { "Naxxramas", "Noth", "10N" }, { "Naxxramas", "Heigan", "10N" } } },
  [40634] = { slot = "Legs", tier = "T7", family = "Lost Conqueror",  pages = { { "Naxxramas", "Gluth", "25N" }, { "Naxxramas", "Thaddius", "25N" }, { "Naxxramas", "4Horsemen", "25N" } } },
  [40635] = { slot = "Legs", tier = "T7", family = "Lost Protector",  pages = { { "Naxxramas", "Gluth", "25N" }, { "Naxxramas", "Thaddius", "25N" }, { "Naxxramas", "4Horsemen", "25N" } } },
  [40636] = { slot = "Legs", tier = "T7", family = "Lost Vanquisher", pages = { { "Naxxramas", "Gluth", "25N" }, { "Naxxramas", "Thaddius", "25N" }, { "Naxxramas", "4Horsemen", "25N" } } },
  -- T7 shoulders (Loatheb 40622-24 / 40637-39)
  [40622] = { slot = "Shoulder", tier = "T7", family = "Lost Conqueror",  pages = { { "Naxxramas", "Loatheb", "10N" } } },
  [40623] = { slot = "Shoulder", tier = "T7", family = "Lost Protector",  pages = { { "Naxxramas", "Loatheb", "10N" } } },
  [40624] = { slot = "Shoulder", tier = "T7", family = "Lost Vanquisher", pages = { { "Naxxramas", "Loatheb", "10N" } } },
  [40637] = { slot = "Shoulder", tier = "T7", family = "Lost Conqueror",  pages = { { "Naxxramas", "Loatheb", "25N" } } },
  [40638] = { slot = "Shoulder", tier = "T7", family = "Lost Protector",  pages = { { "Naxxramas", "Loatheb", "25N" } } },
  [40639] = { slot = "Shoulder", tier = "T7", family = "Lost Vanquisher", pages = { { "Naxxramas", "Loatheb", "25N" } } },
  -- T7 chest (10: 4Horsemen 40610-12; 25: Gluth 40625-27)
  [40610] = { slot = "Chest", tier = "T7", family = "Lost Conqueror",  pages = { { "Naxxramas", "4Horsemen", "10N" } } },
  [40611] = { slot = "Chest", tier = "T7", family = "Lost Protector",  pages = { { "Naxxramas", "4Horsemen", "10N" } } },
  [40612] = { slot = "Chest", tier = "T7", family = "Lost Vanquisher", pages = { { "Naxxramas", "4Horsemen", "10N" } } },
  [40625] = { slot = "Chest", tier = "T7", family = "Lost Conqueror",  pages = { { "Naxxramas", "Gluth", "25N" } } },
  [40626] = { slot = "Chest", tier = "T7", family = "Lost Protector",  pages = { { "Naxxramas", "Gluth", "25N" } } },
  [40627] = { slot = "Chest", tier = "T7", family = "Lost Vanquisher", pages = { { "Naxxramas", "Gluth", "25N" } } },
  -- T7 head (Kel'Thuzad 40616-18 / 40631-33)
  [40616] = { slot = "Head", tier = "T7", family = "Lost Conqueror",  pages = { { "Naxxramas", "Kel'Thuzad", "10N" } } },
  [40617] = { slot = "Head", tier = "T7", family = "Lost Protector",  pages = { { "Naxxramas", "Kel'Thuzad", "10N" } } },
  [40618] = { slot = "Head", tier = "T7", family = "Lost Vanquisher", pages = { { "Naxxramas", "Kel'Thuzad", "10N" } } },
  [40631] = { slot = "Head", tier = "T7", family = "Lost Conqueror",  pages = { { "Naxxramas", "Kel'Thuzad", "25N" } } },
  [40632] = { slot = "Head", tier = "T7", family = "Lost Protector",  pages = { { "Naxxramas", "Kel'Thuzad", "25N" } } },
  [40633] = { slot = "Head", tier = "T7", family = "Lost Vanquisher", pages = { { "Naxxramas", "Kel'Thuzad", "25N" } } },
  -- T8 "Wayward" (oracle: exact per-boss pages, 10N bare / 25Man suffix)
  [45644] = { slot = "Hands", tier = "T8", family = "Wayward Conqueror",  pages = { { "Ulduar", "Freya", "10N" } } },
  [45645] = { slot = "Hands", tier = "T8", family = "Wayward Protector",  pages = { { "Ulduar", "Freya", "10N" } } },
  [45646] = { slot = "Hands", tier = "T8", family = "Wayward Vanquisher", pages = { { "Ulduar", "Freya", "10N" } } },
  [45647] = { slot = "Head", tier = "T8", family = "Wayward Conqueror",  pages = { { "Ulduar", "Mimiron", "10N" } } },
  [45648] = { slot = "Head", tier = "T8", family = "Wayward Protector",  pages = { { "Ulduar", "Mimiron", "10N" } } },
  [45649] = { slot = "Head", tier = "T8", family = "Wayward Vanquisher", pages = { { "Ulduar", "Mimiron", "10N" } } },
  [45650] = { slot = "Legs", tier = "T8", family = "Wayward Conqueror",  pages = { { "Ulduar", "Hodir", "10N" } } },
  [45651] = { slot = "Legs", tier = "T8", family = "Wayward Protector",  pages = { { "Ulduar", "Hodir", "10N" } } },
  [45652] = { slot = "Legs", tier = "T8", family = "Wayward Vanquisher", pages = { { "Ulduar", "Hodir", "10N" } } },
  [45635] = { slot = "Chest", tier = "T8", family = "Wayward Conqueror",  pages = { { "Ulduar", "Yogg", "10N" } } },
  [45636] = { slot = "Chest", tier = "T8", family = "Wayward Protector",  pages = { { "Ulduar", "Yogg", "10N" } } },
  [45637] = { slot = "Chest", tier = "T8", family = "Wayward Vanquisher", pages = { { "Ulduar", "Yogg", "10N" } } },
  [45659] = { slot = "Shoulder", tier = "T8", family = "Wayward Conqueror",  pages = { { "Ulduar", "Thorim", "10N" } } },
  [45660] = { slot = "Shoulder", tier = "T8", family = "Wayward Protector",  pages = { { "Ulduar", "Thorim", "10N" } } },
  [45661] = { slot = "Shoulder", tier = "T8", family = "Wayward Vanquisher", pages = { { "Ulduar", "Thorim", "10N" } } },
  [45641] = { slot = "Hands", tier = "T8", family = "Wayward Conqueror",  pages = { { "Ulduar", "Mimiron", "25N" } } },
  [45642] = { slot = "Hands", tier = "T8", family = "Wayward Protector",  pages = { { "Ulduar", "Mimiron", "25N" } } },
  [45643] = { slot = "Hands", tier = "T8", family = "Wayward Vanquisher", pages = { { "Ulduar", "Mimiron", "25N" } } },
  [45638] = { slot = "Head", tier = "T8", family = "Wayward Conqueror",  pages = { { "Ulduar", "Thorim", "25N" } } },
  [45639] = { slot = "Head", tier = "T8", family = "Wayward Protector",  pages = { { "Ulduar", "Thorim", "25N" } } },
  [45640] = { slot = "Head", tier = "T8", family = "Wayward Vanquisher", pages = { { "Ulduar", "Thorim", "25N" } } },
  [45632] = { slot = "Chest", tier = "T8", family = "Wayward Conqueror",  pages = { { "Ulduar", "Hodir", "25N" } } },
  [45633] = { slot = "Chest", tier = "T8", family = "Wayward Protector",  pages = { { "Ulduar", "Hodir", "25N" } } },
  [45634] = { slot = "Chest", tier = "T8", family = "Wayward Vanquisher", pages = { { "Ulduar", "Hodir", "25N" } } },
  [45653] = { slot = "Legs", tier = "T8", family = "Wayward Conqueror",  pages = { { "Ulduar", "Freya", "25N" } } },
  [45654] = { slot = "Legs", tier = "T8", family = "Wayward Protector",  pages = { { "Ulduar", "Freya", "25N" } } },
  [45655] = { slot = "Legs", tier = "T8", family = "Wayward Vanquisher", pages = { { "Ulduar", "Freya", "25N" } } },
  [45656] = { slot = "Shoulder", tier = "T8", family = "Wayward Conqueror",  pages = { { "Ulduar", "Yogg", "25N" } } },
  [45657] = { slot = "Shoulder", tier = "T8", family = "Wayward Protector",  pages = { { "Ulduar", "Yogg", "25N" } } },
  [45658] = { slot = "Shoulder", tier = "T8", family = "Wayward Vanquisher", pages = { { "Ulduar", "Yogg", "25N" } } },
}

-- T7/T8 tier GEAR (bislists >=2 specs of one class + boss-listed;
-- generated offline 2026-09-15). itemID -> {tier, class, slot}.
M.GEAR_SLOTS = {
  [39192] = { tier = "T7", class = "Warlock", slot = "Hands" },
  [39194] = { tier = "T7", class = "Hunter", slot = "Hands" },
  [39224] = { tier = "T7", class = "Rogue", slot = "Legs" },
  [39237] = { tier = "T8", class = "Rogue", slot = "Shoulder" },
  [39248] = { tier = "T7", class = "Hunter", slot = "Chest" },
  [39249] = { tier = "T7", class = "Warrior", slot = "Shoulder" },
  [39299] = { tier = "T7", class = "Druid", slot = "Hands" },
  [39309] = { tier = "T7", class = "Priest", slot = "Legs" },
  [39310] = { tier = "T7", class = "Priest", slot = "Shoulder" },
  [39386] = { tier = "T7", class = "Rogue", slot = "Chest" },
  [39396] = { tier = "T7", class = "Mage", slot = "Chest" },
  [39399] = { tier = "T7", class = "Rogue", slot = "Head" },
  [39403] = { tier = "T7", class = "Death knight", slot = "Head" },
  [39408] = { tier = "T7", class = "Priest", slot = "Legs" },
  [39704] = { tier = "T8", class = "Warrior", slot = "Shoulder" },
  [39719] = { tier = "T7", class = "Priest", slot = "Shoulder" },
  [39720] = { tier = "T8", class = "Shaman", slot = "Legs" },
  [39724] = { tier = "T8", class = "Shaman", slot = "Chest" },
  [39727] = { tier = "T8", class = "Warrior", slot = "Hands" },
  [39733] = { tier = "T7", class = "Priest", slot = "Hands" },
  [39761] = { tier = "T7", class = "Rogue", slot = "Legs" },
  [39767] = { tier = "T8", class = "Warrior", slot = "Chest" },
  [40060] = { tier = "T8", class = "Priest", slot = "Legs" },
  [40062] = { tier = "T7", class = "Mage", slot = "Chest" },
  [40185] = { tier = "T7", class = "Warrior", slot = "Shoulder" },
  [40194] = { tier = "T7", class = "Priest", slot = "Chest" },
  [40197] = { tier = "T7", class = "Mage", slot = "Hands" },
  [40201] = { tier = "T7", class = "Hunter", slot = "Legs" },
  [40203] = { tier = "T8", class = "Warrior", slot = "Chest" },
  [40234] = { tier = "T8", class = "Druid", slot = "Chest" },
  [40242] = { tier = "T7", class = "Hunter", slot = "Hands" },
  [40261] = { tier = "T8", class = "Warrior", slot = "Hands" },
  [40262] = { tier = "T7", class = "Warrior", slot = "Hands" },
  [40277] = { tier = "T7", class = "Warrior", slot = "Chest" },
  [40283] = { tier = "T7", class = "Shaman", slot = "Chest" },
  [40286] = { tier = "T8", class = "Druid", slot = "Shoulder" },
  [40287] = { tier = "T7", class = "Priest", slot = "Head" },
  [40289] = { tier = "T7", class = "Priest", slot = "Shoulder" },
  [40294] = { tier = "T7", class = "Warrior", slot = "Legs" },
  [40299] = { tier = "T7", class = "Hunter", slot = "Shoulder" },
  [40302] = { tier = "T7", class = "Shaman", slot = "Hands" },
  [40303] = { tier = "T7", class = "Priest", slot = "Hands" },
  [40305] = { tier = "T7", class = "Rogue", slot = "Shoulder" },
  [40315] = { tier = "T7", class = "Death knight", slot = "Shoulder" },
  [40318] = { tier = "T7", class = "Warrior", slot = "Legs" },
  [40319] = { tier = "T7", class = "Rogue", slot = "Chest" },
  [40328] = { tier = "T8", class = "Paladin", slot = "Head" },
  [40329] = { tier = "T7", class = "Rogue", slot = "Head" },
  [40331] = { tier = "T7", class = "Hunter", slot = "Legs" },
  [40333] = { tier = "T7", class = "Rogue", slot = "Legs" },
  [40339] = { tier = "T7", class = "Shaman", slot = "Head" },
  [40344] = { tier = "T7", class = "Warrior", slot = "Head" },
  [40347] = { tier = "T7", class = "Death knight", slot = "Hands" },
  [40351] = { tier = "T8", class = "Mage", slot = "Shoulder" },
  [40352] = { tier = "T7", class = "Shaman", slot = "Legs" },
  [40362] = { tier = "T7", class = "Rogue", slot = "Hands" },
  [40365] = { tier = "T7", class = "Death knight", slot = "Chest" },
  [40376] = { tier = "T7", class = "Mage", slot = "Legs" },
  [40379] = { tier = "T8", class = "Druid", slot = "Legs" },
  [40380] = { tier = "T7", class = "Mage", slot = "Hands" },
  [40381] = { tier = "T7", class = "Priest", slot = "Chest" },
  [40398] = { tier = "T8", class = "Priest", slot = "Legs" },
  [40414] = { tier = "T8", class = "Warrior", slot = "Shoulder" },
  [40437] = { tier = "T8", class = "Rogue", slot = "Shoulder" },
  [40438] = { tier = "T7", class = "Shaman", slot = "Shoulder" },
  [40439] = { tier = "T7", class = "Shaman", slot = "Shoulder" },
  [40451] = { tier = "T7", class = "Hunter", slot = "Head" },
  [40526] = { tier = "T8", class = "Druid", slot = "Chest" },
  [40539] = { tier = "T8", class = "Warrior", slot = "Chest" },
  [40541] = { tier = "T8", class = "Warrior", slot = "Hands" },
  [40543] = { tier = "T7", class = "Warrior", slot = "Head" },
  [40555] = { tier = "T7", class = "Druid", slot = "Shoulder" },
  [40560] = { tier = "T8", class = "Druid", slot = "Legs" },
  [40562] = { tier = "T8", class = "Druid", slot = "Head" },
  [40564] = { tier = "T7", class = "Shaman", slot = "Hands" },
  [40588] = { tier = "T7", class = "Shaman", slot = "Chest" },
  [40589] = { tier = "T8", class = "Warrior", slot = "Legs" },
  [40594] = { tier = "T7", class = "Druid", slot = "Shoulder" },
  [40602] = { tier = "T7", class = "Priest", slot = "Chest" },
  [43990] = { tier = "T7", class = "Druid", slot = "Chest" },
  [43994] = { tier = "T7", class = "Warrior", slot = "Legs" },
  [43995] = { tier = "T7", class = "Priest", slot = "Head" },
  [43998] = { tier = "T7", class = "Warrior", slot = "Chest" },
  [44000] = { tier = "T8", class = "Death knight", slot = "Chest" },
  [44002] = { tier = "T8", class = "Priest", slot = "Chest" },
  [44003] = { tier = "T7", class = "Hunter", slot = "Shoulder" },
  [44006] = { tier = "T8", class = "Warrior", slot = "Head" },
  [44007] = { tier = "T8", class = "Shaman", slot = "Head" },
  [44011] = { tier = "T8", class = "Warrior", slot = "Legs" },
  [45107] = { tier = "T8", class = "Warrior", slot = "Head" },
  [45134] = { tier = "T8", class = "Warrior", slot = "Legs" },
  [45136] = { tier = "T8", class = "Shaman", slot = "Shoulder" },
  [45141] = { tier = "T8", class = "Rogue", slot = "Legs" },
  [45143] = { tier = "T8", class = "Hunter", slot = "Legs" },
  [45150] = { tier = "T8", class = "Mage", slot = "Head" },
  [45164] = { tier = "T8", class = "Hunter", slot = "Head" },
  [45186] = { tier = "T8", class = "Mage", slot = "Shoulder" },
  [45225] = { tier = "T8", class = "Death knight", slot = "Chest" },
  [45227] = { tier = "T8", class = "Warrior", slot = "Shoulder" },
  [45238] = { tier = "T8", class = "Mage", slot = "Legs" },
  [45239] = { tier = "T8", class = "Shaman", slot = "Hands" },
  [45240] = { tier = "T8", class = "Priest", slot = "Chest" },
  [45245] = { tier = "T8", class = "Warrior", slot = "Shoulder" },
  [45248] = { tier = "T8", class = "Warrior", slot = "Legs" },
  [45253] = { tier = "T8", class = "Priest", slot = "Shoulder" },
  [45265] = { tier = "T8", class = "Rogue", slot = "Shoulder" },
  [45272] = { tier = "T8", class = "Priest", slot = "Chest" },
  [45273] = { tier = "T8", class = "Priest", slot = "Hands" },
  [45289] = { tier = "T8", class = "Priest", slot = "Head" },
  [45300] = { tier = "T8", class = "Hunter", slot = "Shoulder" },
  [45320] = { tier = "T8", class = "Warrior", slot = "Shoulder" },
  [45325] = { tier = "T8", class = "Warrior", slot = "Hands" },
  [45329] = { tier = "T8", class = "Hunter", slot = "Head" },
  [45344] = { tier = "T8", class = "Death knight", slot = "Shoulder" },
  [45355] = { tier = "T8", class = "Druid", slot = "Hands" },
  [45356] = { tier = "T8", class = "Druid", slot = "Head" },
  [45358] = { tier = "T8", class = "Druid", slot = "Chest" },
  [45359] = { tier = "T8", class = "Druid", slot = "Shoulder" },
  [45360] = { tier = "T8", class = "Hunter", slot = "Hands" },
  [45361] = { tier = "T8", class = "Hunter", slot = "Head" },
  [45363] = { tier = "T8", class = "Hunter", slot = "Shoulder" },
  [45364] = { tier = "T8", class = "Hunter", slot = "Chest" },
  [45365] = { tier = "T8", class = "Mage", slot = "Head" },
  [45367] = { tier = "T8", class = "Mage", slot = "Legs" },
  [45369] = { tier = "T8", class = "Mage", slot = "Shoulder" },
  [45387] = { tier = "T8", class = "Priest", slot = "Hands" },
  [45388] = { tier = "T8", class = "Priest", slot = "Legs" },
  [45389] = { tier = "T8", class = "Priest", slot = "Chest" },
  [45390] = { tier = "T8", class = "Priest", slot = "Shoulder" },
  [45396] = { tier = "T8", class = "Rogue", slot = "Chest" },
  [45397] = { tier = "T8", class = "Rogue", slot = "Hands" },
  [45398] = { tier = "T8", class = "Rogue", slot = "Head" },
  [45400] = { tier = "T8", class = "Rogue", slot = "Shoulder" },
  [45419] = { tier = "T8", class = "Warlock", slot = "Hands" },
  [45420] = { tier = "T8", class = "Warlock", slot = "Legs" },
  [45421] = { tier = "T8", class = "Warlock", slot = "Chest" },
  [45444] = { tier = "T8", class = "Warrior", slot = "Hands" },
  [45453] = { tier = "T8", class = "Rogue", slot = "Chest" },
  [45464] = { tier = "T8", class = "Mage", slot = "Head" },
  [45468] = { tier = "T8", class = "Priest", slot = "Legs" },
  [45472] = { tier = "T8", class = "Warrior", slot = "Head" },
  [45473] = { tier = "T8", class = "Warrior", slot = "Chest" },
  [45474] = { tier = "T8", class = "Shaman", slot = "Shoulder" },
  [45481] = { tier = "T8", class = "Death knight", slot = "Hands" },
  [45488] = { tier = "T8", class = "Shaman", slot = "Legs" },
  [45497] = { tier = "T8", class = "Shaman", slot = "Head" },
  [45504] = { tier = "T8", class = "Hunter", slot = "Legs" },
  [45514] = { tier = "T8", class = "Priest", slot = "Shoulder" },
  [45519] = { tier = "T8", class = "Druid", slot = "Chest" },
  [45520] = { tier = "T8", class = "Priest", slot = "Hands" },
  [45523] = { tier = "T8", class = "Rogue", slot = "Head" },
  [45524] = { tier = "T8", class = "Warrior", slot = "Chest" },
  [45532] = { tier = "T8", class = "Priest", slot = "Head" },
  [45536] = { tier = "T8", class = "Warrior", slot = "Legs" },
  [45610] = { tier = "T8", class = "Warrior", slot = "Head" },
  [45665] = { tier = "T8", class = "Shaman", slot = "Hands" },
  [45676] = { tier = "T8", class = "Death knight", slot = "Chest" },
  [45677] = { tier = "T8", class = "Warrior", slot = "Shoulder" },
  [45687] = { tier = "T8", class = "Shaman", slot = "Head" },
  [45712] = { tier = "T8", class = "Warrior", slot = "Chest" },
  [45865] = { tier = "T8", class = "Mage", slot = "Chest" },
  [45867] = { tier = "T8", class = "Shaman", slot = "Chest" },
  [45893] = { tier = "T8", class = "Rogue", slot = "Head" },
  [45940] = { tier = "T8", class = "Rogue", slot = "Chest" },
  [45941] = { tier = "T8", class = "Hunter", slot = "Chest" },
  [45943] = { tier = "T8", class = "Shaman", slot = "Hands" },
  [45976] = { tier = "T8", class = "Mage", slot = "Hands" },
  [45982] = { tier = "T8", class = "Warrior", slot = "Legs" },
  [45993] = { tier = "T8", class = "Warrior", slot = "Head" },
  [46012] = { tier = "T8", class = "Priest", slot = "Chest" },
  [46013] = { tier = "T8", class = "Priest", slot = "Shoulder" },
  [46034] = { tier = "T8", class = "Priest", slot = "Legs" },
  [46037] = { tier = "T8", class = "Warrior", slot = "Shoulder" },
  [46043] = { tier = "T8", class = "Warrior", slot = "Hands" },
  [46044] = { tier = "T8", class = "Shaman", slot = "Shoulder" },
  [46045] = { tier = "T8", class = "Shaman", slot = "Hands" },
  [46049] = { tier = "T8", class = "Druid", slot = "Legs" },
  [46068] = { tier = "T8", class = "Shaman", slot = "Shoulder" },
  [46111] = { tier = "T8", class = "Death knight", slot = "Chest" },
  [46113] = { tier = "T8", class = "Death knight", slot = "Hands" },
  [46115] = { tier = "T8", class = "Death knight", slot = "Head" },
  [46116] = { tier = "T8", class = "Death knight", slot = "Legs" },
  [46117] = { tier = "T8", class = "Death knight", slot = "Shoulder" },
  [46123] = { tier = "T8", class = "Rogue", slot = "Chest" },
  [46124] = { tier = "T8", class = "Rogue", slot = "Hands" },
  [46125] = { tier = "T8", class = "Rogue", slot = "Head" },
  [46126] = { tier = "T8", class = "Rogue", slot = "Legs" },
  [46127] = { tier = "T8", class = "Rogue", slot = "Shoulder" },
  [46129] = { tier = "T8", class = "Mage", slot = "Head" },
  [46130] = { tier = "T8", class = "Mage", slot = "Chest" },
  [46131] = { tier = "T8", class = "Mage", slot = "Hands" },
  [46132] = { tier = "T8", class = "Mage", slot = "Hands" },
  [46133] = { tier = "T8", class = "Mage", slot = "Legs" },
  [46134] = { tier = "T8", class = "Mage", slot = "Shoulder" },
  [46135] = { tier = "T8", class = "Warlock", slot = "Hands" },
  [46136] = { tier = "T8", class = "Warlock", slot = "Shoulder" },
  [46137] = { tier = "T8", class = "Warlock", slot = "Chest" },
  [46139] = { tier = "T8", class = "Warlock", slot = "Legs" },
  [46140] = { tier = "T8", class = "Warlock", slot = "Head" },
  [46141] = { tier = "T8", class = "Hunter", slot = "Chest" },
  [46142] = { tier = "T8", class = "Hunter", slot = "Hands" },
  [46143] = { tier = "T8", class = "Hunter", slot = "Head" },
  [46145] = { tier = "T8", class = "Hunter", slot = "Shoulder" },
  [46146] = { tier = "T8", class = "Warrior", slot = "Chest" },
  [46148] = { tier = "T8", class = "Warrior", slot = "Hands" },
  [46149] = { tier = "T8", class = "Warrior", slot = "Shoulder" },
  [46150] = { tier = "T8", class = "Warrior", slot = "Legs" },
  [46151] = { tier = "T8", class = "Warrior", slot = "Head" },
  [46157] = { tier = "T8", class = "Druid", slot = "Shoulder" },
  [46158] = { tier = "T8", class = "Druid", slot = "Hands" },
  [46159] = { tier = "T8", class = "Druid", slot = "Chest" },
  [46160] = { tier = "T8", class = "Druid", slot = "Legs" },
  [46161] = { tier = "T8", class = "Druid", slot = "Head" },
  [46188] = { tier = "T8", class = "Priest", slot = "Hands" },
  [46190] = { tier = "T8", class = "Priest", slot = "Shoulder" },
  [46193] = { tier = "T8", class = "Priest", slot = "Chest" },
  [46194] = { tier = "T8", class = "Druid", slot = "Chest" },
  [46195] = { tier = "T8", class = "Priest", slot = "Legs" },
  [46197] = { tier = "T8", class = "Priest", slot = "Head" },
}

-- Token slot derivation from token NAME prefix (slot is implicit in the
-- item, per the owner's naming convention note). Pairs with TOKEN_PAGES
-- names like "Helm of the Wayward Protector".
M.TOKEN_NAME_SLOT = {
  Helm = "Head", Crown = "Head",
  Spaulders = "Shoulder", Mantle = "Shoulder",
  Chestguard = "Chest", Breastplate = "Chest",
  Gloves = "Hands", Gauntlets = "Hands",
  Leggings = "Legs", Legplates = "Legs",
}

return M
