name: Discord Release Notification

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  discord:
    uses: Xidiuss/Bistooltip/.github/workflows/discord-release.yml@main
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
